### PR TITLE
Create harbour-pomodorohelper-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted.

### CODE REVIEW

**Comment by osanwe** [comment]
Thanks! Could you also translate `Category`, `Add category`, `Edit category`, `Remove category`?

**Comment by eson57** [comment]
Of Course. Did you update .ts files, or do you want translation here in comment?

**Comment by osanwe** [comment]
Thanks. I'll update translation this weekend.

**Comment by osanwe** [comment]
Added.

**Pull request closed without merging**
